[logging]
level = "info"
file = "logs/note-to-ai.log"

[vault]
path = "./vault"
auto_sync = true
index_interval = 300
cache_size = 1000

[ai]
model_path = "./models"
embeddings_path = "./models/all-MiniLM-L6-v2.safetensors"
context_window = 4096
model_registry = "./models/model_registry.toml"

[crypto]
pq_enabled = true
key_path = "./config/keys"
hybrid_mode = true

[swarm]
bootstrap_nodes = []
private_key_path = "./config/swarm.key"
swarm_key_path = "./config/swarm.key"

[signal]
enabled = false
phone_number = ""
device_id = 1

[database]
path = "./db/notetoai.db"
encrypted = true