[logging]
level = "info"
file = "./logs/note-to-ai.log"

[vault]
path = "./vault"
auto_sync = true
index_interval = 300  # seconds
cache_size = 1000     # number of documents

[ai]
model_path = "./models"
embeddings_path = "./models/embeddings"
context_window = 4096
model_registry = "./models/model_registry.toml"

[crypto]
pq_enabled = true
key_path = "./keys"
hybrid_mode = true

[swarm]
bootstrap_nodes = []
private_key_path = "./keys/private.key"
swarm_key_path = "./keys/swarm.key"

[signal]
enabled = true
phone_number = ""
device_id = 1

[database]
path = "./database.db"
encrypted = true